"""add machine lifecycle and warranty fields

Revision ID: 0d960b843070
Revises: 69f81b326aaa
Create Date: 2026-09-09 14:48:42.822354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d960b843070'
down_revision: Union[str, Sequence[str], None] = '69f81b326aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "machines",
        sa.Column("status", sa.String(), nullable=True),
    )
    op.add_column(
        "machines",
        sa.Column("listed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "machines",
        sa.Column("sold_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "machines",
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "machines",
        sa.Column("sale_price", sa.Float(), nullable=True),
    )
    op.add_column(
        "machines",
        sa.Column("has_warranty", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "machines",
        sa.Column("warranty_duration", sa.Integer(), nullable=True),
    )
    op.add_column(
        "machines",
        sa.Column("warranty_duration_unit", sa.String(), nullable=True),
    )
    op.add_column(
        "machines",
        sa.Column("warranty_notes", sa.Text(), nullable=True),
    )

    # Backfill existing machine records.
    op.execute(
        "UPDATE machines SET status = 'listed' WHERE status IS NULL"
    )
    op.execute(
        "UPDATE machines SET has_warranty = false WHERE has_warranty IS NULL"
    )

    # Now that every existing row has a value, enforce NOT NULL.
    op.alter_column("machines", "status", nullable=False)
    op.alter_column("machines", "has_warranty", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'warranty_notes')
    op.drop_column('machines', 'warranty_duration_unit')
    op.drop_column('machines', 'warranty_duration')
    op.drop_column('machines', 'has_warranty')
    op.drop_column('machines', 'sale_price')
    op.drop_column('machines', 'delivered_at')
    op.drop_column('machines', 'sold_at')
    op.drop_column('machines', 'listed_at')
    op.drop_column('machines', 'status')
    # ### end Alembic commands ###
