"""add billing and delivery information to sales

Revision ID: 136a155ce21b
Revises: 33e10d5494b9
Create Date: 2026-09-18 11:04:38.853073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136a155ce21b'
down_revision: Union[str, Sequence[str], None] = '33e10d5494b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column(
        'billing_address_line_1', sa.String(), nullable=True))
    op.add_column('sales', sa.Column(
        'billing_address_line_2', sa.String(), nullable=True))
    op.add_column('sales', sa.Column(
        'billing_city', sa.String(), nullable=True))
    op.add_column('sales', sa.Column(
        'billing_state', sa.String(), nullable=True))
    op.add_column('sales', sa.Column(
        'billing_postal_code', sa.String(), nullable=True))
    op.add_column(
        'sales',
        sa.Column(
            'delivery_same_as_billing',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )
    op.alter_column(
        'sales',
        'delivery_same_as_billing',
        server_default=None
    )
    op.add_column('sales', sa.Column(
        'delivery_address_line_1', sa.String(), nullable=True))
    op.add_column('sales', sa.Column(
        'delivery_address_line_2', sa.String(), nullable=True))
    op.add_column('sales', sa.Column(
        'delivery_city', sa.String(), nullable=True))
    op.add_column('sales', sa.Column(
        'delivery_state', sa.String(), nullable=True))
    op.add_column('sales', sa.Column(
        'delivery_postal_code', sa.String(), nullable=True))
    op.drop_index(op.f('ix_sales_machine_id'), table_name='sales')
    op.create_index(op.f('ix_sales_machine_id'), 'sales',
                    ['machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_machine_id'), table_name='sales')
    op.create_index(op.f('ix_sales_machine_id'),
                    'sales', ['machine_id'], unique=True)
    op.drop_column('sales', 'delivery_postal_code')
    op.drop_column('sales', 'delivery_state')
    op.drop_column('sales', 'delivery_city')
    op.drop_column('sales', 'delivery_address_line_2')
    op.drop_column('sales', 'delivery_address_line_1')
    op.drop_column('sales', 'delivery_same_as_billing')
    op.drop_column('sales', 'billing_postal_code')
    op.drop_column('sales', 'billing_state')
    op.drop_column('sales', 'billing_city')
    op.drop_column('sales', 'billing_address_line_2')
    op.drop_column('sales', 'billing_address_line_1')
    # ### end Alembic commands ###
