"""add equipment profiles

Revision ID: 33e10d5494b9
Revises: b8fe275e0723
Create Date: 2026-09-11 14:35:53.693888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e10d5494b9'
down_revision: Union[str, Sequence[str], None] = 'b8fe275e0723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('best_for', sa.Text(), nullable=True),
    sa.Column('not_for', sa.Text(), nullable=True),
    sa.Column('key_benefits', sa.Text(), nullable=True),
    sa.Column('common_uses', sa.Text(), nullable=True),
    sa.Column('faq', sa.Text(), nullable=True),
    sa.Column('comparison_notes', sa.Text(), nullable=True),
    sa.Column('manufacturer_url', sa.String(), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_profiles_manufacturer'), 'equipment_profiles', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_equipment_profiles_model'), 'equipment_profiles', ['model'], unique=False)
    op.add_column('machines', sa.Column('equipment_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key( "fk_machines_equipment_profile_id", "machines", "equipment_profiles", ["equipment_profile_id"], ["id"],)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_machines_equipment_profile_id", 'machines', type_='foreignkey')
    op.drop_column('machines', 'equipment_profile_id')
    op.drop_index(op.f('ix_equipment_profiles_model'), table_name='equipment_profiles')
    op.drop_index(op.f('ix_equipment_profiles_manufacturer'), table_name='equipment_profiles')
    op.drop_table('equipment_profiles')
    # ### end Alembic commands ###
