"""add service records

Revision ID: b8fe275e0723
Revises: e2fb583da3fa
Create Date: 2026-09-10 16:44:41.750048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fe275e0723'
down_revision: Union[str, Sequence[str], None] = 'e2fb583da3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('warranty_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('reported_issue', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('work_performed', sa.Text(), nullable=True),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('covered_by_warranty', sa.Boolean(), nullable=False),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('parts_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('technician', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['warranty_id'], ['warranties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_id'), 'service_records', ['id'], unique=False)
    op.create_index(op.f('ix_service_records_machine_id'), 'service_records', ['machine_id'], unique=False)
    op.create_index(op.f('ix_service_records_sale_id'), 'service_records', ['sale_id'], unique=False)
    op.create_index(op.f('ix_service_records_warranty_id'), 'service_records', ['warranty_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_records_warranty_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_sale_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_machine_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_id'), table_name='service_records')
    op.drop_table('service_records')
    # ### end Alembic commands ###
