"""add warranties

Revision ID: e2fb583da3fa
Revises: 5b3c3688f25e
Create Date: 2026-09-10 16:33:38.063049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2fb583da3fa'
down_revision: Union[str, Sequence[str], None] = '5b3c3688f25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warranties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('duration_unit', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('coverage_terms', sa.Text(), nullable=True),
    sa.Column('exclusions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warranties_id'), 'warranties', ['id'], unique=False)
    op.create_index(op.f('ix_warranties_sale_id'), 'warranties', ['sale_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warranties_sale_id'), table_name='warranties')
    op.drop_index(op.f('ix_warranties_id'), table_name='warranties')
    op.drop_table('warranties')
    # ### end Alembic commands ###
